Master
Anton-Somikkk/music pull request #6
Opened 2022-09-25 21:48 UTC by Anton-Somikkk

2022-09-26 06:13 UTC, mrerberg requested changes

2022-09-26 06:13 UTC, mrerberg commented on src/components/protected-route.js
> +  if (isAllowed !== "token=Name") {
Приставка is означает, что в данном prop лежит boolean значение. А ты сравниваешь со строкой. Тебе это сравнение надо сделать, когда ты уже готовишь значение для  isAllowed пропа

2022-09-26 06:13 UTC, mrerberg commented on src/components/protected-route.js
>    return children;
https://reactrouter.com/en/main/components/outlet

2022-09-26 06:13 UTC, mrerberg commented on src/css/style.scss
>  //.centerblock {
Почему так много закомментированного кода?

2022-09-26 06:13 UTC, mrerberg commented on src/pages/authorization.js
> +		setValue(event.target.value);
Что с форматированием кода?

2022-09-26 06:13 UTC, mrerberg commented on src/components/protected-route.js
>    return children;
Посмотри в лекции, как я его использую и для чего

2022-09-27 06:02 UTC, mrerberg requested changes

2022-09-27 06:02 UTC, mrerberg commented on src/App.js
> +// eslint-disable-next-line import/no-cycle
?

2022-09-27 06:02 UTC, mrerberg commented on src/components/Wrapper/Wrapper.js
> +/* eslint-disable import/prefer-default-export */
Отключи правило, чтобы не комментить везде

2022-09-27 06:02 UTC, mrerberg commented on src/routes.jsx
> +      <Route path="/authorization" element={<Authorization />} />
Можно сделать и для данных путей аналог ProtectedRoute, чтобы если пользак залогине, редиректило на главную

2022-09-28 05:56 UTC, mrerberg requested changes

2022-09-28 05:56 UTC, mrerberg commented on src/routes.jsx
>  /* eslint-disable import/named */
?

2022-09-28 05:56 UTC, mrerberg commented on src/components/protected-route.js
> +export function ProtectedRouteMain({ redirectPath = "/", isAllowed }) {
Мне кажется, что подобрано не самое лучшее название. Main мне ничего не говорит. Надо как-то обыграть, что это компонент для неавторизированной заны

2022-09-29 08:14 UTC, mrerberg approved these changes

2022-09-29 08:14 UTC, mrerberg commented on src/components/CentralBlockContent/CentralBlockContent.js
> +                <S.PlayListTitleCol02>ИСПОЛНИТЕЛЬ</S.PlayListTitleCol02>
Сделай капслок везде с помощью css

2022-10-06 18:10 UTC, merged

2022-10-06 18:12 UTC, Anton-Somikkk commented on src/components/CentralBlockContent/CentralBlockContent.js
> +                <S.PlayListTitleCol02>ИСПОЛНИТЕЛЬ</S.PlayListTitleCol02>
Ок, сделаю!

2022-10-06 18:12 UTC, Anton-Somikkk commented on src/components/protected-route.js
> +export function ProtectedRouteMain({ redirectPath = "/", isAllowed }) {
Переименовал!